/brc_arm_motor_driver:
  ros__parameters:
    motor_controllers:
      odrive:
        serial: 128
      roboclaw:
        baud: 115200
        identifiers: [128, 129, 130]

    # Must be in order of homing
    joints:
      gantry:
        controller: "odrive"
        motor_num: 1
        type: "arm"
        reduction: 1863.512284
        speed: [10000, 1000000, 10000]
        PIDMM: [1, 1, 1, 1, 0, 0, 100000]
      midarm1:
        controller: "roboclaw"
        identifier: 128
        motor_num: 1
        type: "arm"
        reduction: 5255.871815
        speed: [10000, 1000000, 10000]
        PIDMM: [1, 1, 1, 1, 0, 0, 100000]
      midarm2:
        controller: "roboclaw"
        identifier: 128
        motor_num: 2
        type: "arm"
        reduction: 5255.871815
        speed: [10000, 1000000, 10000]
        PIDMM: [1, 1, 1, 1, 0, 0, 100000]
      wrist1:
        controller: "roboclaw"
        identifier: 129
        motor_num: 1
        type: "arm"
        reduction: 30273.82166
        speed: [10000, 1000000, 10000]
        PIDMM: [1, 1, 1, 1, 0, 0, 100000]
      wrist2:
        controller: "roboclaw"
        identifier: 129
        motor_num: 2
        type: "arm"
        reduction: 81.52866242
        speed: [10000, 1000000, 10000]
        PIDMM: [1, 1, 1, 1, 0, 0, 100000]
      EEbase:
        controller: "roboclaw"
        identifier: 130
        motor_num: 1
        type: "arm"
        reduction: 163.0573248
        speed: [10000, 1000000, 10000]
        PIDMM: [1, 1, 1, 1, 0, 0, 100000]
      RLink1:
        controller: "roboclaw"
        identifier: 130
        motor_num: 2
        type: "EE"
        current_limit: 0.4
