/brc_arm_motor_driver:
  ros__parameters:
    motor_controllers:
      odrive:
        serial: 128
      roboclaw:
        baud: 115200
        identifiers: [128, 129, 130]
    
    #Encoder mode: 7  6            5              43210
                  #0, reverse enc, reverse motor, 00000
    # Must be in order of homing
    joints:
      gantry:
        controller: "odrive"
        motor_num: 1
        type: "arm"
        trap_traj_const: [10, 10, 5, 5, 0]
      midarm1:
        controller: "roboclaw"
        identifier: 128
        motor_num: 1
        type: "arm"
        encoder_mode: 0b00100000
        reduction: 5255.871815
        speed: [10000, 1000000, 10000]
        PID_VEL: [7.66, 0.827, 0.0, 3000]
        PID_POS: [8.56, 0.001, 0.001, 1, 0, 0, 100000]
      midarm2:
        controller: "roboclaw"
        identifier: 128
        motor_num: 2
        type: "arm"
        encoder_mode: 0b00100000
        reduction: 5255.871815
        speed: [10000, 1000000, 10000]
        PID_VEL: [8.53, 1.023, 0.0, 3000]
        PID_POS: [4.0, 0.001, 0.001, 1, 0, 0, 100000]
      wrist1:
        controller: "roboclaw"
        identifier: 129
        motor_num: 1
        type: "arm"
        encoder_mode: 0b00000000
        reduction: 30273.82166
        speed: [10000, 1000000, 10000]
        PID_VEL: [8.53, 1.023, 0.0, 3000]
        PID_POS: [7.25, 0.0, 0.0, 1, 0, 0, 100000]
      diff1:
        controller: "roboclaw"
        identifier: 129
        motor_num: 2
        type: "arm"
        encoder_mode: 0b00100000
        reduction: 81.52866242
        speed: [10000, 1000000, 10000]
        PID_VEL: [8.53, 1.023, 0.0, 3000]
        PID_POS: [7.25, 0.0, 0.0, 1, 0, 0, 100000]
      diff2:
        controller: "roboclaw"
        identifier: 130
        motor_num: 1
        type: "arm"
        encoder_mode: 0b00000000
        reduction: 163.0573248
        speed: [10000, 1000000, 10000]
        PID_VEL: [8.53, 1.023, 0.0, 3000]
        PID_POS: [7.25, 0.0, 0.0, 1, 0, 0, 100000]
      RLink1:
        controller: "roboclaw"
        identifier: 130
        motor_num: 2
        type: "EE"
        currentLimit: 0.4
